version: '3'
services:
  nakama:
    build: .
    volumes:
      - ./data:/nakama/data
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address ${DATABASE_URI} &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address ${DATABASE_URI}        
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  data: